CREATE TABLE IF NOT EXISTS action (
    userid BIGINT NOT NULL,
    modid BIGINT NOT NULL,
    reason VARCHAR(256) NOT NULL,
    messageid BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    time TIMESTAMP NOT NULL,
    id SERIAL
);

CREATE TABLE IF NOT EXISTS mutes (
    modid BIGINT NOT NULL,
    userid BIGINT NOT NULL,
    time TIMESTAMP NOT NULL,
    expire TIMESTAMP NOT NULL,
    id BIGINT NOT NULL
);